In [6]:
import numpy as np

In [7]:
empa=np.empty((3,4))
print("Empty array:")
print(empa)

Empty array:
[[8.57281081e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.42336543e-057 6.81855360e-091 1.69175720e-052]
 [1.29150858e+160 4.71379346e-062 3.99910963e+252 7.62810881e+169]]


In [8]:
empb=np.full((5,4),55,dtype=float)
print(empb)

[[55. 55. 55. 55.]
 [55. 55. 55. 55.]
 [55. 55. 55. 55.]
 [55. 55. 55. 55.]
 [55. 55. 55. 55.]]


In [9]:
a = np.array([1,2,3,4,5])

In [10]:
a

array([1, 2, 3, 4, 5])

In [11]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
a.shape

(5,)

In [13]:
b.shape

(2, 3)

In [14]:
a.ndim

1

In [15]:
b.ndim

2

In [16]:
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('float64')

In [18]:
ab = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(ab)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
ab[1, 5]

13

In [23]:
ab[0, :2]

array([1, 2])

In [24]:
ab[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
ab[:, 2]

array([ 3, 10])

In [26]:
ab[0, 1:-1:2]

array([2, 4, 6])

In [27]:
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [28]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
b=np.full((2,3),2)
print(b)

[[2 2 2]
 [2 2 2]]
